import {describe,it,expect,vi,afterEach} from 'vitest';
import {createElement} from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {TransitionAssignments} from '../src/AdminSeasonTransition';
import {transitionChoices,transitionErrors,transitionApi,type TransitionPlan} from '../src/transition-admin';
const plan:TransitionPlan={id:1,sourceSeasonId:1,sourceSeasonNumber:32,targetSeasonNumber:33,status:'draft',targetSeason:null,issues:[],applicationBlockers:[],assignments:[{userId:'hidden-id',fullName:'Ana',isActive:false,fromDivisionCode:'B',proposedDivisionCode:'A',confirmedDivisionCode:null,proposalSource:'COPA_B_GUARANTEE_OVERRIDE',proposalReason:'Campeona Copa B',requiresReview:true,confirmationReason:null}]};
afterEach(()=>vi.unstubAllGlobals());
describe('Transición Admin UI',()=>{
 it('muestra actual, propuesta, origen, revisión e inactividad con nombres',()=>{const html=renderToStaticMarkup(createElement(TransitionAssignments,{plan,choices:transitionChoices(plan),disabled:false,onChange:()=>{}}));expect(html).toContain('Ana · Inactivo');expect(html).toContain('Actual: Liga B → Propuesta: Liga A');expect(html).toContain('Ascenso por Copa B con corrimiento');expect(html).toContain('Requiere revisión Admin');expect(html).not.toContain('hidden-id');});
 it('exige motivo al revisar o cambiar y mantiene destinos confirmados al recuperar',()=>{const choices=transitionChoices(plan);expect(transitionErrors(plan,choices).join()).toContain('motivo');choices[0].reason='Revisado';expect(transitionErrors(plan,choices)).toEqual([]);const p={...plan,assignments:[{...plan.assignments[0],requiresReview:false}]};choices[0].reason=' ';choices[0].divisionCode='B';expect(transitionErrors(p,choices).join()).toContain('motivo');const confirmed={...p,assignments:[{...p.assignments[0],confirmedDivisionCode:'B',confirmationReason:'Ajuste'}]};expect(transitionChoices(confirmed)[0]).toEqual({userId:'hidden-id',divisionCode:'B',reason:'Ajuste'});});
 it('no acepta destinos fuera de A/B ni participantes omitidos',()=>{expect(transitionErrors(plan,[]).length).toBeGreaterThan(0);expect(transitionErrors(plan,[{userId:'hidden-id',divisionCode:'C',reason:'x'}]).join()).toContain('A/B');});
 it('usa lectura sin mutación y separa generar, confirmar y aplicar',async()=>{const calls:any[]=[];vi.stubGlobal('fetch',async(url:string,init:any)=>{calls.push([url,init.method,init.body]);return new Response(JSON.stringify({plan}));});await transitionApi.load(1);await transitionApi.generate(1);await transitionApi.confirm(1,transitionChoices(plan));await transitionApi.apply(1);expect(calls.map(c=>c[1])).toEqual(['GET','POST','PUT','POST']);expect(calls[0][2]).toBeUndefined();expect(calls[2][0]).toContain('/transition-plans/1/confirm');expect(calls[3][0]).toContain('/transition-plans/1/apply');});
});
