// Participant read model: persisted public sporting data only. No refresh/mutation.
export async function competitionOverview(db: D1Database, userId: string, requested: number) {
  const editions = (await db.prepare(`SELECT season_number AS seasonNumber,name,status FROM tafa_seasons WHERE status <> 'draft' ORDER BY season_number DESC`).all<{seasonNumber:number;name:string;status:string}>()).results;
  const edition = requested > 0 ? editions.find(s => s.seasonNumber === requested) : editions.find(s => s.status === 'active');
  if (!edition) return { currentUserId:userId, editions, season:null };
  const season = await db.prepare('SELECT id FROM tafa_seasons WHERE season_number=?').bind(edition.seasonNumber).first<{id:number}>();
  const id=season!.id;
  const [competitions,stages,links,members,people,encounters,results,history,segments,qualifiers] = await Promise.all([
    db.prepare(`SELECT id,code,display_name AS displayName,family,status,division_id AS divisionId FROM competitions WHERE season_id=? ORDER BY sort_order,id`).bind(id).all(),
    db.prepare(`SELECT s.id,s.competition_id AS competitionId,s.name,s.code,s.stage_type AS type,s.sequence,s.status FROM competition_stages s JOIN competitions c ON c.id=s.competition_id WHERE c.season_id=? ORDER BY s.sequence`).bind(id).all(),
    db.prepare(`SELECT l.id,l.competition_id AS competitionId,l.stage_id AS stageId,l.round_id AS roundId,l.sequence,r.name,r.status FROM competition_round_links l JOIN competitions c ON c.id=l.competition_id JOIN rounds r ON r.id=l.round_id WHERE c.season_id=? AND l.purpose='NORMAL' ORDER BY l.sequence`).bind(id).all(),
    db.prepare(`SELECT e.id AS entryId,e.competition_id AS competitionId,e.status,e.entry_type AS entryType,m.user_id AS userId,u.full_name AS fullName,m.valid_from_round_id AS validFrom,m.valid_to_round_id AS validTo FROM competition_entries e JOIN competitions c ON c.id=e.competition_id JOIN competition_entry_members m ON m.entry_id=e.id JOIN users u ON u.id=m.user_id WHERE c.season_id=? ORDER BY m.id`).bind(id).all(),
    db.prepare(`SELECT u.id AS userId,u.full_name AS fullName,d.id AS divisionId,d.code AS division,d.name AS league FROM season_division_members m JOIN users u ON u.id=m.user_id JOIN season_divisions d ON d.id=m.division_id WHERE m.season_id=?`).bind(id).all(),
    db.prepare(`SELECT e.id,e.stage_id AS stageId,l.round_id AS roundId,e.entry_a_id AS entryAId,e.entry_b_id AS entryBId,e.score_a AS scoreA,e.score_b AS scoreB,e.status,e.winner_entry_id AS winnerEntryId,e.admin_confirmed_at AS confirmedAt,e.resolution,e.slot_key AS slot FROM competition_encounters e JOIN competition_stages s ON s.id=e.stage_id JOIN competitions c ON c.id=s.competition_id LEFT JOIN competition_round_links l ON l.id=e.round_link_id WHERE c.season_id=? AND s.stage_type='KNOCKOUT' ORDER BY s.sequence,e.id`).bind(id).all(),
    db.prepare(`SELECT r.competition_id AS competitionId,r.entry_id AS entryId,r.result_code AS resultCode,r.final_position AS position,s.name AS stageName FROM competition_results r JOIN competitions c ON c.id=r.competition_id LEFT JOIN competition_stages s ON s.id=r.stage_id WHERE c.season_id=?`).bind(id).all(),
    db.prepare(`SELECT c.code,c.id AS competitionId,s.season_number AS seasonNumber,s.name AS seasonName,r.result_code AS resultCode,CASE WHEN e.entry_type='DUO' THEN COALESCE((SELECT group_concat(full_name, ' + ') FROM (SELECT DISTINCT u.id,u.full_name FROM competition_entry_members m JOIN users u ON u.id=m.user_id WHERE m.entry_id=e.id ORDER BY m.id)),e.display_name) ELSE e.display_name END AS name FROM competition_results r JOIN competitions c ON c.id=r.competition_id JOIN tafa_seasons s ON s.id=c.season_id JOIN competition_entries e ON e.id=r.entry_id WHERE s.status <> 'draft' AND r.result_code IN ('CHAMPION','RUNNER_UP') ORDER BY s.season_number DESC`).all(),
    db.prepare(`SELECT seg.id,seg.name,seg.sequence,l.stage_id AS stageId,r.name AS roundName FROM competition_round_segments seg JOIN competition_round_links l ON l.id=seg.round_link_id JOIN competitions c ON c.id=l.competition_id JOIN rounds r ON r.id=l.round_id WHERE c.season_id=? ORDER BY l.sequence,seg.sequence`).bind(id).all(),
    db.prepare(`SELECT q.entry_id AS entryId,q.source_stage_id AS sourceStageId,q.target_stage_id AS targetStageId FROM competition_stage_qualifiers q JOIN competition_stages st ON st.id=q.source_stage_id JOIN competitions c ON c.id=st.competition_id WHERE c.season_id=?`).bind(id).all(),
  ]);
  return {currentUserId:userId,editions,season:{...edition,id,competitions:competitions.results,stages:stages.results,links:links.results,members:members.results,people:people.results,encounters:encounters.results,results:results.results,history:history.results,segments:segments.results,qualifiers:qualifiers.results}};
}
