export const CORE_PRODUCTION_TABLES = [
  'users',
  'sessions',
  'rounds',
  'matches',
  'predictions',
  'round_submissions',
  'prediction_scores',
  'audit_log',
  'league_seasons',
  'league_rounds',
  'league_participants',
  'prediction_history',
  'official_predictions',
  'prediction_submission_events',
] as const;

export const T32_PRODUCTION_TABLES = [
  'tafa_seasons',
  'season_divisions',
  'season_division_members',
  'competitions',
  'competition_stages',
  'competition_entries',
  'competition_entry_members',
  'competition_round_links',
  'competition_round_segments',
  'competition_round_segment_matches',
  'competition_groups',
  'competition_group_entries',
  'competition_encounters',
  'competition_entry_bonuses',
  'competition_tiebreaks',
  'competition_tiebreak_entries',
  'competition_tiebreak_rounds',
  'season_division_movements',
  'iffhs_season_components',
  'iffhs_season_totals',
  'competition_results',
  'competition_stage_qualifiers',
  'competition_survival_round_settings',
  'competition_survival_results',
  'competition_qualification_slots',
  'competition_champions_nodes',
  'season_transition_plans',
  'season_transition_assignments',
  'competition_survival_tiebreaks',
] as const;

export const REQUIRED_PRODUCTION_TABLES = [
  'promiedos_cache',
  ...CORE_PRODUCTION_TABLES,
  ...T32_PRODUCTION_TABLES,
] as const;

export const REQUIRED_PRODUCTION_COLUMNS = {
  "promiedos_cache": ["kind","cache_key","payload_json","fetched_at","expires_at","requested_at"],
  "audit_log": ["id","actor_user_id","action","entity_type","entity_id","before_json","after_json","created_at"],
  "competition_champions_nodes": ["id","competition_id","node_code","label","branch","sequence","source_a_type","source_a_ref","source_b_type","source_b_ref","stage_id","round_link_id","encounter_id","created_at","updated_at"],
  "competition_encounters": ["id","stage_id","group_id","round_link_id","segment_id","slot_key","entry_a_id","entry_b_id","score_a","score_b","status","winner_entry_id","resolution","admin_confirmed_at","created_at","updated_at"],
  "competition_entries": ["id","competition_id","entry_type","display_name","status","seed_position","source_json","created_at","updated_at"],
  "competition_entry_bonuses": ["id","competition_id","stage_id","round_link_id","entry_id","points","reason","created_at"],
  "competition_entry_members": ["id","entry_id","user_id","valid_from_round_id","valid_to_round_id","joined_at","left_at"],
  "competition_group_entries": ["group_id","entry_id","seed_position"],
  "competition_groups": ["id","stage_id","code","name","sequence","created_at"],
  "competition_qualification_slots": ["id","competition_id","slot_code","slot_name","source_type","source_json","proposed_user_id","confirmed_user_id","confirmed_entry_id","status","replacement_reason","confirmed_by_user_id","created_at","updated_at"],
  "competition_results": ["id","competition_id","entry_id","stage_id","result_code","final_position","detail_json","confirmed_by_user_id","confirmed_at","updated_at"],
  "competition_round_links": ["id","competition_id","stage_id","round_id","sequence","purpose","label","created_at"],
  "competition_round_segment_matches": ["segment_id","match_id","sequence"],
  "competition_round_segments": ["id","round_link_id","code","name","sequence","created_at"],
  "competition_stage_qualifiers": ["id","source_stage_id","target_stage_id","entry_id","source_group_id","qualification_type","source_position","ranking_order","reason_json","confirmed_by_user_id","confirmed_at"],
  "competition_stages": ["id","competition_id","code","name","stage_type","sequence","status","settings_json","created_at","updated_at"],
  "competition_survival_results": ["id","stage_id","round_link_id","entry_id","base_points","bonus_points","total_points","position","decision","next_bonus_points","confirmed_by_user_id","confirmed_at","members_json"],
  "competition_survival_round_settings": ["round_link_id","stage_id","eliminate_count","bonus_by_position_json","updated_by_user_id","created_at","updated_at"],
  "competition_survival_tiebreaks": ["round_link_id","tiebreak_id","source_points_json"],
  "competition_tiebreak_entries": ["tiebreak_id","entry_id"],
  "competition_tiebreak_rounds": ["tiebreak_id","round_id","sequence"],
  "competition_tiebreaks": ["id","competition_id","stage_id","encounter_id","status","winner_entry_id","resolution","created_at","resolved_at"],
  "competitions": ["id","season_id","division_id","code","canonical_name","display_name","family","status","sort_order","settings_json","created_at","updated_at","finished_at"],
  "iffhs_season_components": ["id","season_number","user_id","competition_code","component_code","base_value_scaled","multiplier_scaled","points_scaled","detail_json","source","calculated_at"],
  "iffhs_season_totals": ["season_number","user_id","total_points_scaled","source","calculated_at"],
  "league_participants": ["season_id","user_id","joined_at","eligible_from_slot"],
  "league_rounds": ["season_id","round_id","slot_number","created_at"],
  "league_seasons": ["id","name","status","created_at","updated_at","finished_at"],
  "matches": ["id","round_id","provider","provider_fixture_id","competition_name","competition_logo_url","home_team_provider_id","home_team_name","home_team_logo_url","away_team_provider_id","away_team_name","away_team_logo_url","kickoff_at","status","elapsed_minutes","match_type","home_score_current","away_score_current","home_score_regulation","away_score_regulation","winning_team_provider_id","qualified_team_provider_id","went_to_extra_time","went_to_penalties","is_void","result_finalized_at","last_synced_at","created_at","updated_at"],
  "official_predictions": ["id","user_id","match_id","predicted_home_score","predicted_away_score","predicted_extra_team_provider_id","is_admin_override","version","updated_at","source"],
  "prediction_history": ["id","round_id","user_id","event_type","actor_kind","created_at","before_json","after_json"],
  "prediction_scores": ["prediction_id","result_type","base_points","extra_points","total_points","is_provisional","calculated_at"],
  "prediction_submission_events": ["id","round_id","user_id","match_id","event_type","actor_kind","created_at","fields_json","before_json","after_json"],
  "predictions": ["id","user_id","match_id","predicted_home_score","predicted_away_score","predicted_extra_team_provider_id","is_admin_override","created_at","updated_at"],
  "round_submissions": ["id","round_id","user_id","first_submitted_at","last_submitted_at","submission_count"],
  "rounds": ["id","name","status","published_at","finished_at","created_at","updated_at","category"],
  "season_division_members": ["season_id","division_id","user_id","source","assigned_at"],
  "season_division_movements": ["id","season_id","user_id","from_division_id","to_division_id","reason","status","created_at","confirmed_at"],
  "season_divisions": ["id","season_id","code","name","sort_order","is_active","created_at"],
  "season_transition_assignments": ["id","plan_id","user_id","from_division_code","proposed_division_code","confirmed_division_code","proposal_source","proposal_reason","requires_review","confirmation_reason","created_at","updated_at"],
  "season_transition_plans": ["id","source_season_id","target_season_number","status","issues_json","created_by_user_id","confirmed_by_user_id","applied_by_user_id","created_at","updated_at","confirmed_at","applied_at"],
  "sessions": ["id","user_id","token_hash","expires_at","created_at"],
  "tafa_seasons": ["id","season_number","name","status","created_at","updated_at","started_at","finished_at"],
  "users": ["id","full_name","phone_normalized","password_hash","role","is_active","created_at","updated_at"],
} as const;

export const REQUIRED_PRODUCTION_TRIGGERS = [
  'prediction_history_no_update',
  'prediction_history_no_delete',
  'official_events_no_update',
  'official_events_no_delete',
  'validate_official_submission_insert',
  'promote_official_submission_insert',
  'validate_official_submission_update',
  'promote_official_submission_update',
  'audit_official_insert',
  'invalidate_official_score_insert',
  'audit_official_update',
  'invalidate_official_score_update',
] as const;

export const MINIMUM_PRODUCTION_MIGRATION = '0015_promiedos_cache.sql';

export const REQUIRED_PRODUCTION_MIGRATIONS = ["0001_initial.sql","0002_league_seasons.sql","0003_league_entry_slot.sql","0004_prediction_history.sql","0005_official_predictions.sql","0006_competition_engine.sql","0007_iffhs.sql","0008_competition_results.sql","0009_stage_qualifiers.sql","0010_duos_survival.sql","0011_competition_qualification_slots.sql","0012_champions_bracket_nodes.sql","0013_season_transition_plan.sql","0014_duos_admin.sql","0015_promiedos_cache.sql"] as const;
