import {useEffect,useState} from 'react';
import {competitionHref,readCompetition} from './participant-competitions';
import './participant-competitions.css';
export type LeagueRow={position:number;userId:string;fullName:string;points:number;fulls:number;partials:number;errors:number;extras:number;zone?:{code:string;label:string}|null};
export type LeagueData={currentUserId:string;season:{name:string;seasonNumber:number};competition:{displayName:string};division:{code:string;name:string};provisional:boolean;linkedRounds:{roundId:number;sequence:number;name:string;status:string}[];standings:LeagueRow[]};
export function LeagueTable({rows,user,season}:{rows:LeagueRow[];user:string;season?:number}) {return <table className="sport-table league-sport-table"><thead><tr><th>POS</th><th><span className="sr-only">Escudo</span></th><th>Participante</th><th>PTS</th>{['Plenos','Parciales','Errores','Extras'].map(label=><th className="league-secondary" key={label}>{label}</th>)}</tr></thead><tbody>{rows.map((r,index)=><tr key={r.userId} className={`${r.userId===user?'sport-mine':''} ${r.zone?.code!==rows[index-1]?.zone?.code?'sport-zone-start':''} sport-zone-${r.zone?.code??'none'}`}><td>{r.position}</td><td><span className="sport-avatar" aria-hidden="true">{r.fullName.slice(0,2)}</span></td><th scope="row"><a href={`#/club/participante/${encodeURIComponent(r.userId)}${season?`?season=${season}`:''}`}>{r.fullName}{r.userId===user&&<small>Vos</small>}</a></th><td className="sport-points">{r.points}</td>{[r.fulls,r.partials,r.errors,r.extras].map((n,i)=><td className="league-secondary" key={i}>{n}</td>)}</tr>)}</tbody></table>;}
export default function LeagueView({initialLeagueCode,seasonNumber,preview}:{initialLeagueCode?:'LIGA_A'|'LIGA_B';seasonNumber?:number;preview?:LeagueData}={}) {
 const [data,setData]=useState<LeagueData|null>(preview??null);const [error,setError]=useState('');const [loading,setLoading]=useState(!preview);const [revision,setRevision]=useState(0);const [empty,setEmpty]=useState(false);
 useEffect(()=>{if(preview)return;const controller=new AbortController();setLoading(true);setError('');setEmpty(false);
 (async()=>{let code=initialLeagueCode;
 if(!seasonNumber){const current=await readCompetition<{season:{division:{code:string}|null}|null}>('/api/competition-engine/current',controller.signal);if(!current.season){const old=await readCompetition<{season:any}>('/api/league',controller.signal);if(controller.signal.aborted)return;if(old.season){setData({currentUserId:old.season.currentUserId,season:{name:old.season.name,seasonNumber:0},competition:{displayName:old.season.name},division:{code:'',name:'Liga anterior'},provisional:old.season.status!=='finished',linkedRounds:old.season.rounds.map((r:any)=>({roundId:r.id,sequence:r.slot,name:r.name,status:r.status})),standings:old.season.standings});}else setEmpty(true);return;}code??=current.season.division?.code==='B'?'LIGA_B':'LIGA_A';}
 const next=await readCompetition<LeagueData>(`/api/competition-engine/leagues/${code??'LIGA_A'}/standings${seasonNumber?`?season=${seasonNumber}`:''}`,controller.signal);if(!controller.signal.aborted)setData(next);
 })().catch(()=>{if(!controller.signal.aborted)setError('No pudimos cargar la Liga. Intentá de nuevo.');}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[initialLeagueCode,seasonNumber,revision,preview]);
 if(loading)return <p role="status">Cargando Liga…</p>;if(error)return <section><p role="alert">{error}</p><button className="button" onClick={()=>setRevision(n=>n+1)}>Reintentar</button></section>;if(empty||!data)return <section className="reference-section"><h1>Liga</h1><p>Todavía no hay una temporada disponible.</p></section>;
 return <div className="participant-competitions"><header className="sport-heading"><span className="eyebrow">{data.season.name}</span><h1>{data.competition.displayName}</h1><p>{data.linkedRounds.length}/5 Fechas · {data.standings.length} participantes</p></header>{data.division.code&&<nav className="sport-tabs" aria-label="División">{['A','B'].map(code=><a key={code} aria-current={code===data.division.code?'page':undefined} href={competitionHref(`LIGA_${code}`,data.season.seasonNumber)}>Liga {code}</a>)}</nav>}<section className="reference-section"><div className="section-heading"><h2>Tabla</h2><button className="button button--ghost" onClick={()=>setRevision(n=>n+1)}>Actualizar</button></div>{data.provisional&&<p>Tabla provisional · quedan resultados o Fechas por cerrar.</p>}<LeagueTable rows={data.standings} user={data.currentUserId} season={data.season.seasonNumber||undefined}/><div className="sport-zone-legend">{Array.from(new Map(data.standings.filter(r=>r.zone).map(r=>[r.zone!.code,r.zone!])).values()).map(z=><span className={`sport-zone-${z.code}`} key={z.code}>{z.label}</span>)}</div>{data.standings.some(r=>r.zone)&&<p className="sport-footnote">Zonas de referencia. La clasificación y los movimientos se confirman por separado.</p>}{!data.standings.length&&<p>Todavía no hay participantes en esta Liga.</p>}</section><details className="reference-section"><summary>Fechas de la Liga</summary>{data.linkedRounds.map(r=><p key={r.roundId}>{r.sequence}. {r.name} · {r.status==='finished'?'Finalizada':r.status==='open'?'Abierta':'Por comenzar'}</p>)}</details></div>;
}
