import { profileHref } from './participant-profile';
import {useEffect,useState} from 'react';
import {phaseName,competitionHref,competitionSlugs,entryMembers,entryName,participation,readCompetition,type Overview,type Season,type Competition,type Encounter} from './participant-competitions';
import LeagueView from './LeagueView';
import './participant-competitions.css';

function EntryPeople({s,id,round}:{s:Season;id:number|null;round:number|null}) { const members=entryMembers(s,id,round);return <>{members.length?members.map((m,i)=><span key={m.userId}>{i>0?' + ':''}<a href={profileHref(m.userId,s.seasonNumber)}>{m.fullName}</a></span>):'Por definir'}</>; }
export function SportingEncounter({s,e,user,label}:{s:Season;e:Encounter;user:string;label?:string}) {
 const mine=[e.entryAId,e.entryBId].some(id=>entryMembers(s,id,e.roundId).some(m=>m.userId===user));
 return <article className={`sport-encounter ${mine?'sport-encounter--mine':''}`}><small>{label ?? s.links.find(l=>l.roundId===e.roundId)?.name ?? 'Fecha por definir'}</small>{[e.entryAId,e.entryBId].map((id,index)=><div key={index} className={e.confirmedAt&&id!==null&&e.winnerEntryId===id?'sport-winner':''}><span>{id===null&&e.resolution==='bye'?'Libre':<EntryPeople s={s} id={id} round={e.roundId}/>}</span><strong>{(index===0?e.scoreA:e.scoreB)??'—'}</strong>{e.confirmedAt&&id!==null&&e.winnerEntryId===id&&<small>Ganador</small>}</div>)}<small>{e.confirmedAt?'Resultado confirmado':e.status==='tied'?'Desempate TAFA pendiente':e.status==='live'?'En juego · provisional':e.status==='finished'?'Resultado pendiente de confirmación':'Pendiente'}</small></article>;
}
export function CompetitionDirectory({data,league}:{data:Overview;league?:{code:string;position:number;points:number}|null}) {
 const s=data.season;if(!s)return <section className="reference-section"><h1>Competiciones</h1><p>Todavía no hay una temporada disponible.</p><p>Las competiciones aparecerán cuando comience la temporada.</p><a className="button button--ghost" href="#/competiciones/liga">Consultar Liga</a></section>;
 const own=s.people.find(p=>p.userId===data.currentUserId)?.divisionId;
 return <><header className="sport-heading"><span className="eyebrow">{s.name}</span><h1>Competiciones</h1><p>Tu temporada, competición por competición.</p></header><div className="sport-directory">{[...s.competitions].sort((a,b)=>Number(b.family==='LEAGUE'&&b.divisionId===own)-Number(a.family==='LEAGUE'&&a.divisionId===own)).map(c=>{
 const stages=s.stages.filter(st=>st.competitionId===c.id);
 const encounters=s.encounters.filter(e=>stages.some(st=>st.id===e.stageId)&&[e.entryAId,e.entryBId].some(id=>entryMembers(s,id,e.roundId).some(m=>m.userId===data.currentUserId)));
 const latest=encounters.at(-1);
 return <a key={c.id} href={competitionHref(c.code,s.seasonNumber)} className="sport-directory-row"><span className="competition-emblem" aria-hidden="true">{c.displayName.split(' ').map(n=>n[0]).join('').slice(0,3)}</span><span><h2>{c.displayName}</h2><p>{participation(s,c,data.currentUserId)}{league?.code===c.code ? ` · ${league.position}.º · ${league.points} PTS` : ''}</p>{latest?<small>{phaseName(stages.find(st=>st.id===latest.stageId)?.name)} · {entryName(s,latest.entryAId,latest.roundId)} vs {entryName(s,latest.entryBId,latest.roundId)} · {latest.scoreA??'—'}–{latest.scoreB??'—'}</small>:<small>{stages.find(st=>st.status==='active')?.name??({draft:'Por comenzar',active:'En juego',finished:'Finalizada',archived:'Histórica'}[c.status]??'Pendiente')}</small>}</span><span aria-hidden="true">›</span></a>;
 })}</div></>;
}
type Row={position:number;entryId:number;userId?:string;fullName?:string;displayName?:string;points?:number;totalPoints?:number;gf?:number;gd?:number;won?:number;provisional?:boolean;decision?:string;members?:{userId?:string;fullName:string}[]};
type Group={id:number;name:string;provisional?:boolean;standings:Row[];fixtures?:{id:number;segmentId:number;entryAId:number;entryBId:number;scoreA:number;scoreB:number;complete:boolean}[]};
export function GroupTable({rows,user,s}:{rows:Row[];user:string;s:Season}) {return <table className="sport-table"><thead><tr><th>Pos</th><th>Participante</th><th>PTS</th>{rows.some(r=>r.gf!==undefined)&&<><th>DG</th><th>GF</th><th>PG</th></>}</tr></thead><tbody>{rows.map(r=><tr key={r.entryId} className={(r.members?r.members.some(m=>m.userId===user):r.userId===user||s.members.some(m=>m.entryId===r.entryId&&m.userId===user))?'sport-mine':''}><td>{r.position}</td><th scope="row">{r.members?.map(m=>m.fullName).join(' + ')||r.fullName||r.displayName||entryName(s,r.entryId,null)}{s.qualifiers?.some(q=>q.entryId===r.entryId)&&<small>Clasificado · {phaseName(s.stages.find(st=>st.id===s.qualifiers?.find(q=>q.entryId===r.entryId)?.targetStageId)?.name)}</small>}{r.decision&&<small>{({eliminated:'Eliminado',survived:'Continúa',qualified:'Clasificado'}[r.decision]??'Confirmado')}</small>}</th><td className="sport-points">{r.points??r.totalPoints??'—'}</td>{r.gf!==undefined&&<><td>{r.gd}</td><td>{r.gf}</td><td>{r.won}</td></>}</tr>)}</tbody></table>;}
function CompetitionBody({s,c,user}:{s:Season;c:Competition;user:string}) {
 const [tab,setTab]=useState('actual');const [retry,setRetry]=useState(0);const [extra,setExtra]=useState<{groups?:Group[];rows?:Row[];confirmed?:boolean;bracket?:any[]}|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(false);
 const stages=s.stages.filter(st=>st.competitionId===c.id);const links=s.links.filter(l=>l.competitionId===c.id&&stages.some(st=>st.id===l.stageId&&st.type==='SURVIVAL_TABLE'));
 const [duoLink,setDuoLink]=useState(links.at(-1)?.id??0);const groupStage=stages.find(st=>['ACCUMULATIVE_GROUPS','ROUND_ROBIN_GROUPS'].includes(st.type));
 useEffect(()=>{const controller=new AbortController();setError('');setExtra(null);
 const url=c.code==='COPA_CAMPEONES'?`/api/competition-engine/competitions/${c.id}/champions/bracket`:groupStage?.type==='ACCUMULATIVE_GROUPS'?`/api/competition-engine/cups/${c.code}/groups?season=${s.seasonNumber}`:groupStage?`/api/competition-engine/stages/${groupStage.id}/total/groups`:duoLink?`/api/competition-engine/round-links/${duoLink}/duos/table`:null;
 if(url){setLoading(true);readCompetition<any>(url,controller.signal).then(value=>{if(!controller.signal.aborted)setExtra(value);}).catch(()=>{if(!controller.signal.aborted)setError('No pudimos cargar la tabla o el cuadro. Reintentá en unos instantes.');}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});}return()=>controller.abort();},[c.id,duoLink,retry]);
 const encounters=s.encounters.filter(e=>stages.some(st=>st.id===e.stageId));const mine=encounters.filter(e=>[e.entryAId,e.entryBId].some(id=>entryMembers(s,id,e.roundId).some(m=>m.userId===user)));
 const history=s.history.filter(h=>h.code===c.code);const editions=[...new Set(history.map(h=>h.seasonNumber))];
 const results=s.results.filter(r=>r.competitionId===c.id).sort((a,b)=>(a.position??999)-(b.position??999));
 return <><header className="sport-heading"><span className="eyebrow">{s.name}</span><h1>{c.displayName}</h1><p>{participation(s,c,user)==='No participás'?`No participás en esta edición de ${c.displayName}.`:participation(s,c,user)}</p></header><nav className="sport-tabs" aria-label="Vistas de competición">{[['actual','Actual'],['cuadro',groupStage?'Grupos y cuadro':links.length?'Tabla y cuadro':'Cuadro'],['historial','Historial']].map(([key,name])=><button key={key} aria-pressed={tab===key} onClick={()=>setTab(key)}>{name}</button>)}</nav>
 {tab==='historial'?<section className="reference-section"><h2>Historial</h2>{editions.length?editions.map(n=><a className="sport-history" key={n} href={competitionHref(c.code,n)}><strong>T{n}</strong><span>Campeón: {history.find(h=>h.seasonNumber===n&&h.resultCode==='CHAMPION')?.name??'Sin definir'}<br/>Subcampeón: {history.find(h=>h.seasonNumber===n&&h.resultCode==='RUNNER_UP')?.name??'Sin definir'}</span><span>Ver edición ›</span></a>):<p>Todavía no hay historial cargado para esta competencia.</p>}</section>:<>
 {tab==='actual'&&<section className="reference-section"><h2>Tu recorrido</h2>{mine.length?<div className="sport-rounds">{mine.map(e=><div key={e.id}><h3>{phaseName(stages.find(st=>st.id===e.stageId)?.name)}</h3><SportingEncounter s={s} e={e} user={user}/></div>)}</div>:<p>Todavía no hay cruces asignados para vos. Podés consultar toda la edición en la tabla o el cuadro.</p>}{results.length>0&&<><h2>Resultados confirmados</h2>{c.code==='COPA_DUOS'&&<p>Integrantes que formaron parte de cada dúo en esta edición, incluidas las sustituciones.</p>}{results.map(r=><p key={r.entryId}><strong>{r.position?`${r.position}.º · `:''}{c.code==='COPA_DUOS'?[...new Map(s.members.filter(m=>m.entryId===r.entryId).map(m=>[m.userId,m.fullName])).values()].join(' + '):entryName(s,r.entryId,null)}</strong> · {({CHAMPION:'Campeón',RUNNER_UP:'Subcampeón',THIRD:'Tercero'}[r.resultCode]??(r.stageName?phaseName(r.stageName):'Participación finalizada'))}</p>)}</>}</section>}
 {tab==='cuadro'&&<>{loading&&<p role="status">Cargando información…</p>}{error&&<div><p role="alert">{error}</p><button className="button" onClick={()=>setRetry(n=>n+1)}>Reintentar</button></div>}{extra?.groups&&[...extra.groups].sort((a,b)=>Number(b.standings.some(r=>r.userId===user||s.members.some(m=>m.entryId===r.entryId&&m.userId===user)))-Number(a.standings.some(r=>r.userId===user||s.members.some(m=>m.entryId===r.entryId&&m.userId===user)))).map(g=><section className="reference-section" key={g.id}><h2>{g.name}</h2>{g.provisional&&<p>Tabla provisional · clasificación pendiente</p>}<div className="sport-table-scroll"><GroupTable rows={g.standings} user={user} s={s}/></div>{g.fixtures&&<details><summary>Mini-fechas y resultados</summary>{g.fixtures.map(f=><p key={f.id}>{s.segments.find(seg=>seg.id===f.segmentId)?.name??'Mini-fecha'} · {entryName(s,f.entryAId,null)} {f.scoreA}–{f.scoreB} {entryName(s,f.entryBId,null)} · {f.complete?'Definitivo':'Provisional'}</p>)}</details>}</section>)}
 {links.length>0&&<section className="reference-section"><label className="field"><span>Fecha de Copa Dúos</span><select value={duoLink} onChange={e=>setDuoLink(Number(e.target.value))}>{links.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label>{extra?.rows&&<><p>{extra.confirmed?'Resultados confirmados':'Tabla provisional'}</p><GroupTable rows={extra.rows} user={user} s={s}/></>}</section>}
 {c.code==='COPA_CAMPEONES'&&extra?.bracket?<div className="sport-rounds">{['UPPER','LOWER','FINAL'].map(branch=><section key={branch}><h2>{{UPPER:'Rama superior',LOWER:'Rama inferior',FINAL:'Final'}[branch]}</h2>{extra.bracket!.filter(n=>n.branch===branch).map(n=><SportingEncounter key={n.id} user={user} s={s} label={n.label} e={{id:n.id,stageId:n.stageId,roundId:n.round?.id??null,entryAId:n.sourceA.entryId,entryBId:n.sourceB.entryId,scoreA:n.encounter?.scoreA??null,scoreB:n.encounter?.scoreB??null,winnerEntryId:n.encounter?.winnerEntryId??null,confirmedAt:n.encounter?.adminConfirmedAt??null,status:n.encounter?.status??'pending',resolution:n.encounter?.resolution??null,slot:n.code}}/>)}</section>)}</div>:<div className="sport-rounds">{stages.filter(st=>st.type==='KNOCKOUT').map(st=><section key={st.id}><h2>{phaseName(st.name)}</h2>{encounters.filter(e=>e.stageId===st.id).map(e=><SportingEncounter key={e.id} s={s} e={e} user={user}/>)}{!encounters.some(e=>e.stageId===st.id)&&<p>Cruces por definir.</p>}</section>)}</div>}
 {!loading&&!error&&!encounters.length&&!extra?.groups?.length&&!extra?.rows?.length&&!extra?.bracket?.length&&<p>La información de esta edición aparecerá cuando esté configurada.</p>}</>}
 </>}</>;
}
export default function ParticipantCompetitionsPage({route,preview}:{route:string;preview?:Overview}) {
 const [data,setData]=useState<Overview|null>(preview??null);const [legacyPerson,setLegacyPerson]=useState<{userId:string;fullName:string;division:string;league:string}|null>(null);const [league,setLeague]=useState<{code:string;position:number;points:number}|null>(null);const [error,setError]=useState('');const [revision,setRevision]=useState(0);
 const query=route.split('?')[1]??'';const path=route.split('?')[0];const requested=new URLSearchParams(query).get('season');
 useEffect(()=>{if(preview)return;const controller=new AbortController();setData(null);setError('');readCompetition<Overview>(`/api/competition-engine/overview${requested?`?season=${encodeURIComponent(requested)}`:''}`,controller.signal).then(d=>{if(!controller.signal.aborted)setData(d);}).catch(()=>{if(!controller.signal.aborted)setError('No pudimos cargar las competiciones.');});return()=>controller.abort();},[requested,revision,preview]);
 useEffect(()=>{setLeague(null);if(preview||!data?.season||path!=='competiciones')return;const s=data.season;const own=s.people.find(p=>p.userId===data.currentUserId);if(!own)return;const controller=new AbortController();readCompetition<{standings:{userId:string;position:number;points:number}[]}>(`/api/competition-engine/leagues/LIGA_${own.division}/standings?season=${s.seasonNumber}`,controller.signal).then(value=>{const mine=value.standings.find(r=>r.userId===data.currentUserId);if(mine&&!controller.signal.aborted)setLeague({code:`LIGA_${own.division}`,position:mine.position,points:mine.points});}).catch(()=>{});return()=>controller.abort();},[data,path,preview]);
 useEffect(()=>{setLegacyPerson(null);if(!data||data.season||!path.startsWith('club/participante/'))return;const controller=new AbortController();readCompetition<{season:{name:string;standings:{userId:string;fullName:string}[]}|null}>('/api/league',controller.signal).then(value=>{const p=value.season?.standings.find(p=>encodeURIComponent(p.userId)===path.slice('club/participante/'.length));if(p&&!controller.signal.aborted)setLegacyPerson({...p,division:'',league:value.season!.name});}).catch(()=>{});return()=>controller.abort();},[data,path]);
 if(error)return <section><p role="alert">{error}</p><button className="button" onClick={()=>setRevision(n=>n+1)}>Reintentar</button></section>;
 if(!data)return <p role="status">Cargando competiciones…</p>;
 const s=data.season;const slug=path.split('/')[1];const c=s?.competitions.find(c=>competitionSlugs[c.code]===slug);
 const personId=path.startsWith('club/participante/')?path.slice('club/participante/'.length):null;
 const person=s?.people.find(p=>encodeURIComponent(p.userId)===personId)??legacyPerson;
 return <div className="participant-competitions"><a href="#/competiciones" className="button button--ghost">Todas las competiciones</a>{data.editions.length>0&&<label className="field sport-edition"><span>Edición</span><select value={s?.seasonNumber??''} onChange={e=>{window.location.hash=`#/${path}?season=${e.target.value}`;}}><option value="" disabled>Elegí una temporada</option>{data.editions.map(e=><option key={e.seasonNumber} value={e.seasonNumber}>T{e.seasonNumber} · {e.name}</option>)}</select></label>}
 {personId?<section className="reference-section"><span className="avatar">{person?.fullName.slice(0,2)??'—'}</span><h1>{person?.fullName??'Participante no disponible en esta edición'}</h1><p>{person?.league}</p><a className="button" href={person?.division?competitionHref(`LIGA_${person.division}`,s?.seasonNumber):'#/competiciones/liga'}>Volver a Liga</a></section>:!s||!slug?<CompetitionDirectory data={data} league={league}/>:c?.family==='LEAGUE'?<><LeagueView key={`${c.code}-${s.seasonNumber}`} initialLeagueCode={c.code as 'LIGA_A'|'LIGA_B'} seasonNumber={s.seasonNumber}/><CompetitionHistory s={s} c={c}/></>:c?<CompetitionBody key={c.id} s={s} c={c} user={data.currentUserId}/>:<p>Esta competición no está disponible en esta edición.</p>}
 </div>;
}


export function CompetitionHistory({s,c}:{s:Season;c:Competition}){const history=s.history.filter(h=>h.code===c.code);return <section className="reference-section"><h2>Historial</h2>{history.length?[...new Set(history.map(h=>h.seasonNumber))].map(n=><a className="sport-history" key={n} href={competitionHref(c.code,n)}><strong>T{n}</strong><span>Campeón: {history.find(h=>h.seasonNumber===n&&h.resultCode==='CHAMPION')?.name??'Sin definir'}<br/>Subcampeón: {history.find(h=>h.seasonNumber===n&&h.resultCode==='RUNNER_UP')?.name??'Sin definir'}</span><span>Ver edición ›</span></a>):<p>Todavía no hay historial cargado para esta competencia.</p>}</section>;}
